services:
  _defaults:
    autowire: true
    autoconfigure: true

  SymPress\StarterTheme\View\WordPressExtension:
    tags: [twig.extension]

  SymPress\StarterTheme\View\TemplateResolver:
    public: true
  SymPress\StarterTheme\WordPress\Context: ~

  SymPress\StarterTheme\View\Renderer:
    public: true

  SymPress\StarterTheme\WordPress\Theme:
    public: true
