<?php

declare(strict_types=1);

require dirname(__DIR__) . '/vendor/autoload.php';

use PhpParser\Node\Expr\FuncCall;
use PhpParser\Node\Name;
use PhpParser\Node\Scalar\String_;
use PhpParser\NodeFinder;
use PhpParser\ParserFactory;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;
use Twig\Node\Expression\ConstantExpression;
use Twig\Node\Expression\FunctionExpression;
use Twig\Node\Node;

$root = dirname(__DIR__);
$messages = [];
$record = static function (string $name, array $args, string $reference) use (&$messages): void {
    if (!in_array($name, ['__', '_e', 'esc_html__', 'esc_attr__', 'esc_html_e', 'esc_attr_e', '_x', '_n'], true) || !isset($args[0])) {
        return;
    }
    $context = $name === '_x' ? ($args[1] ?? '') : '';
    $plural = $name === '_n' ? ($args[1] ?? '') : '';
    $key = $context . "\x04" . $args[0] . "\x04" . $plural;
    $messages[$key] ??= ['id' => $args[0], 'context' => $context, 'plural' => $plural, 'refs' => []];
    $messages[$key]['refs'][] = $reference;
};
$parser = (new ParserFactory())->createForNewestSupportedVersion();
$finder = new NodeFinder();
$phpFiles = [new SplFileInfo($root . '/functions.php'), new SplFileInfo($root . '/comments.php'), new SplFileInfo($root . '/index.php')];
foreach (['src', 'patterns'] as $directory) {
    foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root . '/' . $directory)) as $file) {
        if ($file->isFile() && $file->getExtension() === 'php') {
            $phpFiles[] = $file;
        }
    }
}
foreach ($phpFiles as $file) {
    if (str_contains($file->getPathname(), '/patterns/')) {
        preg_match_all('/^\s*\*\s*(?:Title|Description):\s*(.+)$/m', file_get_contents($file->getPathname()), $headers);
        foreach ($headers[1] as $header) {
            $record('__', [trim($header)], substr($file->getPathname(), strlen($root) + 1));
        }
    }
    foreach ($finder->findInstanceOf($parser->parse(file_get_contents($file->getPathname())), FuncCall::class) as $call) {
        if (!$call->name instanceof Name) {
            continue;
        }
        $args = [];
        foreach ($call->getArgs() as $index => $arg) {
            if ($arg instanceof \PhpParser\Node\Arg && $arg->value instanceof String_) {
                $args[$index] = $arg->value->value;
            }
        }
        $function = $call->name->toString();
        $domainIndex = match ($function) { '_x' => 2, '_n' => 3, default => 1 };
        if (($args[$domainIndex] ?? null) !== 'sympress-starter') {
            continue;
        }
        $record($function, $args, substr($file->getPathname(), strlen($root) + 1) . ':' . $call->getStartLine());
    }
}
$loader = new FilesystemLoader($root . '/resources/views');
$twig = new Environment($loader);
foreach (['TemplateRuntime', 'TranslationRuntime', 'EscapingRuntime', 'QueryRuntime'] as $runtime) {
    $twig->addExtension(new Twig\Extension\AttributeExtension('SymPress\\TwigBundle\\WordPress\\Runtime\\' . $runtime));
}
$visit = static function (Node $node, string $file) use (&$visit, $record): void {
    if ($node instanceof FunctionExpression) {
        $args = [];
        foreach ($node->getNode('arguments') as $index => $arg) {
            if ($arg instanceof ConstantExpression && is_string($arg->getAttribute('value'))) {
                $args[$index] = $arg->getAttribute('value');
            }
        }
        $record($node->getAttribute('name'), $args, 'resources/views/' . $file . ':' . $node->getTemplateLine());
    }
    foreach ($node as $child) {
        $visit($child, $file);
    }
};
foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root . '/resources/views')) as $file) {
    if ($file->isFile() && str_ends_with($file->getFilename(), '.twig')) {
        $name = substr($file->getPathname(), strlen($root . '/resources/views/'));
        if (preg_match('/^Template Name:\s*(.+)$/m', file_get_contents($file->getPathname()), $header)) {
            $record('__', [trim($header[1])], 'resources/views/' . $name);
        }
        $visit($twig->parse($twig->tokenize($loader->getSourceContext($name))), $name);
    }
}
preg_match_all('/^(?:Theme Name|Description):\s*(.+)$/m', file_get_contents($root . '/style.css'), $headers);
foreach ($headers[1] as $header) {
    $record('__', [trim($header)], 'style.css');
}
$settings = json_decode(file_get_contents($root . '/theme.json'), true, 512, JSON_THROW_ON_ERROR)['settings'];
foreach ([$settings['color']['palette'], $settings['typography']['fontFamilies'], $settings['typography']['fontSizes'], $settings['spacing']['spacingSizes']] as $presets) {
    foreach ($presets as $preset) {
        $record('__', [$preset['name']], 'theme.json');
    }
}
ksort($messages);
$quote = static fn (string $text): string => '"' . addcslashes($text, "\\\"\n\r\t") . '"';
$version = json_decode(file_get_contents(dirname(__DIR__) . '/package.json'), true, 512, JSON_THROW_ON_ERROR)['version'];
$output = "# Generated by composer i18n; edit source strings, not this file.\nmsgid \"\"\nmsgstr \"\"\n\"Project-Id-Version: SymPress Starter {$version}\\n\"\n\"Content-Type: text/plain; charset=UTF-8\\n\"\n\"MIME-Version: 1.0\\n\"\n";
foreach ($messages as $message) {
    sort($message['refs']);
    $output .= "\n#: " . implode(' ', array_unique($message['refs'])) . "\n";
    $formatText = str_replace('%%', '', $message['id'] . ' ' . $message['plural']);
    if (preg_match('/%(?:[0-9]+\$)?[-+0-9. ]*[bcdeEfFgGhHosuxX]/', $formatText)) {
        $output .= "#, php-format\n";
    }
    if ($message['context'] !== '') {
        $output .= 'msgctxt ' . $quote($message['context']) . "\n";
    }
    $output .= 'msgid ' . $quote($message['id']) . "\n";
    $output .= $message['plural'] !== '' ? 'msgid_plural ' . $quote($message['plural']) . "\nmsgstr[0] \"\"\nmsgstr[1] \"\"\n" : "msgstr \"\"\n";
}
$target = $root . '/languages/sympress-starter.pot';
if (in_array('--check', $argv, true)) {
    if (!is_file($target) || file_get_contents($target) !== $output) {
        fwrite(STDERR, "Translation catalog is stale. Run composer i18n.\n");
        exit(1);
    }
} else {
    file_put_contents($target, $output);
}
echo 'Extracted ' . count($messages) . " PHP and Twig messages.\n";
