name: Dependency compatibility

on:
  schedule:
    - cron: '38 4 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compatibility:
    permissions:
      contents: read
      issues: write
    uses: sympress/workflows/.github/workflows/dependency-canary.yml@d38b2d9e40eb5b0cdcb84102761af748e3d155b8
    with:
      php_version: '8.5'
      run_node_build: true
