name: Dependency compatibility

on:
  schedule:
    - cron: '38 4 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compatibility:
    permissions:
      contents: read
      issues: write
    uses: sympress/workflows/.github/workflows/dependency-canary.yml@78d083a9a0176cf0252318b0c69fc64938a727d6
    with:
      php_version: '8.5'
      run_node_build: true
