name: Dependency compatibility

on:
  schedule:
    - cron: '38 4 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compatibility:
    permissions:
      contents: read
      issues: write
    uses: sympress/workflows/.github/workflows/dependency-canary.yml@a044303b8492b0c6be48bd9c9fccdc36fb0a9794
    with:
      php_version: '8.5'
      run_node_build: true
